--- 
abstract: Model class of MogileFS::Client on Catalyst
author: Toru Yamaguchi
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-MogileFS-Client
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp::Clan: 0
  Catalyst: 0
  Catalyst::Exception: 0
  Catalyst::Model: 0
  File::Slurp: 0
  MogileFS::Client: 0
  Scalar::Util: 0
version: 0.06
